repos:
- repo: local
  hooks:
    - id: fix non-ascii quotes
      name: fix-non-ascii-quotes
      language: python
      entry: scripts/fix-non-ascii-quotes.py
      types: [json]
      pass_filenames: true
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: check-yaml
    - id: check-json
    - id: pretty-format-json
      args: ["--autofix", "--no-sort-keys", "--no-ensure-ascii"]
    - id: end-of-file-fixer
    - id: trailing-whitespace
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.15.0
  hooks:
    - id: check-github-workflows
    - id: check-jsonschema
      name: "Check Artifacts Valid JSON Schema"
      files: ^definitions/
      types: [json]
      args: ["--check-metaschema"]
