repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: check-yaml
    - id: check-json
    - id: pretty-format-json
      args: ["--autofix", "--no-sort-keys"]
    - id: end-of-file-fixer
    - id: trailing-whitespace
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.15.0
  hooks:
    - id: check-jsonschema
      name: "Check Artifacts Valid JSON Schema"
      files: ^definitions/
      types: [json]
      args: ["--check-metaschema"]
